/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens.mc;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class SistemaTela2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SistemaTela2.class.getName());

    /**
     * Creates new form SistemaTela2
     */
    public SistemaTela2() {
        initComponents();
    }
    private Boolean validacoes(){
        if (jTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo NOME deve ser preenchido.");
            jTextFieldNome.requestFocus();
            return false;
        }
        if (jTextFieldCPF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"O campo CPF deve ser preenchido.");
             jTextFieldCPF.requestFocus();
            return false;
           
        }
        if(!jRadioButtonMasculino.isSelected()&& !jRadioButtonMasculino.isSelected()){
            JOptionPane.showMessageDialog(null,"Opcao de genero nao informada.");
            return false;
        }
        if(!jRadioButtonFeminino.isSelected()&& !jRadioButtonFeminino.isSelected()){
            JOptionPane.showMessageDialog(null,"Opcao de genero nao informada.");
            return false;
       
    }
        if(!jCheckBox1.isSelected()){
            JOptionPane.showMessageDialog(null,"Aceite os termos antes de continuar.");
            return false;
           
    }
        return true;
  }        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMasculino = new javax.swing.ButtonGroup();
        buttonGroupFeminino = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelCadastro = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jRadioButtonFeminino = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCadastro.setFont(new java.awt.Font("Swis721 Ex BT", 2, 14)); // NOI18N
        jLabelCadastro.setText("Cadastro do Cliente");

        jLabelNome.setFont(new java.awt.Font("Siemens Sans SC Black", 0, 14)); // NOI18N
        jLabelNome.setText("Nome:");

        jTextFieldNome.addActionListener(this::jTextFieldNomeActionPerformed);

        jLabelCPF.setFont(new java.awt.Font("Siemens Sans SC Black", 0, 14)); // NOI18N
        jLabelCPF.setText("CPF:");

        jLabel1.setFont(new java.awt.Font("Siemens Sans SC Black", 0, 14)); // NOI18N
        jLabel1.setText("Cidade:");

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", " ", "ADRIANÓPOLIS", " ", "AGUDOS DO SUL", " ", "ALMIRANTE TAMANDARÉ", " ", "ANTONINA", " ", "ANTONIO OLINTO", " ", "ARAPOTI", " ", "ARAUCÁRIA", " ", "BALSA NOVA", " ", "BITURUNA", " ", "BOA VENTURA DE SÃO ROQUE", " ", "BOCAIÚVA DO SUL", " ", "CAMPINA DO SIMÃO", " ", "CAMPINA GRANDE DO SUL", " ", "CAMPO DO TENENTE", " ", "CAMPO LARGO", " ", "CAMPO MAGRO", " ", "CAMPO MOURÃO", " ", "CANDÓI", " ", "CANTAGALO", " ", "CARAMBEÍ", " ", "CASTRO", " ", "CERRO AZUL", " ", "COLOMBO", " ", "CONTENDA", " ", "CRUZ MACHADO", " ", "CURITIBA", " ", "CURIÚVA", " ", "DOUTOR ULYSSES", " ", "FAZENDA RIO GRANDE", " ", "FERNANDES PINHEIRO", " ", "FOZ DO JORDÃO", " ", "GENERAL CARNEIRO", " ", "GOIOXIM", " ", "GUAMIRANGA", " ", "GUARAPUAVA", " ", "GUARAQUEÇABA", " ", "GUARATUBA", " ", "IMBAÚ", " ", "IMBITUVA", " ", "INÁCIO MARTINS", " ", "IPIRANGA", " ", "IRATI", " ", "ITAPERUÇU", " ", "IVAÍ", " ", "JAGUARIAÍVA", " ", "LAPA", " ", "LARANJAL", " ", "MALLET", " ", "MANDIRITUBA", " ", "MATINHOS", " ", "MATO RICO", " ", "MORRETES", " ", "NOVA TEBAS", " ", "ORTIGUEIRA", " ", "PALMEIRA", " ", "PALMITAL", " ", "PARANAGUÁ", " ", "PAULA FREITAS", " ", "PAULO FRONTIN", " ", "PIÊN", " ", "PINHAIS", " ", "PINHÃO", " ", "PIRAÍ DO SUL", " ", "PIRAQUARA", " ", "PITANGA", " ", "PONTA GROSSA", " ", "PONTAL DO PARANÁ", " ", "PORTO AMAZONAS", " ", "PORTO VITÓRIA", " ", "PRUDENTÓPOLIS", " ", "QUATRO BARRAS", " ", "QUITANDINHA", " ", "REBOUÇAS", " ", "RESERVA", " ", "RESERVA DO IGUAÇU", " ", "RIO AZUL", " ", "RIO BRANCO DO SUL", " ", "RIO NEGRO", " ", "SANTA MARIA DO OESTE", " ", "SÃO JOÃO DO TRIUNFO", " ", "SÃO JOSÉ DOS PINHAIS", " ", "SÃO MATEUS DO SUL", " ", "SENGÉS", " ", "TEIXEIRA SOARES", " ", "TELÊMACO BORBA", " ", "TIBAGI", " ", "TIJUCAS DO SUL", " ", "TUNAS DO PARANÁ", " ", "TURVO", " ", "UNIÃO DA VITÓRIA", " ", "VENTANIA" }));
        jComboBoxCidade.addActionListener(this::jComboBoxCidadeActionPerformed);

        jLabel2.setFont(new java.awt.Font("Siemens Sans SC Black", 0, 14)); // NOI18N
        jLabel2.setText("Gênero:");

        jRadioButtonMasculino.setText("Masculino");
        jRadioButtonMasculino.addActionListener(this::jRadioButtonMasculinoActionPerformed);

        jRadioButtonFeminino.setText("Feminino");

        jCheckBox1.setText("Aceito os termos de utilização do sistema");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addComponent(jLabelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelCPF)))
                        .addGap(0, 245, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCPF)
                                    .addComponent(jTextFieldNome)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonMasculino)
                                        .addGap(51, 51, 51)
                                        .addComponent(jRadioButtonFeminino))
                                    .addComponent(jCheckBox1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastro)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPF)
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonMasculino)
                    .addComponent(jRadioButtonFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jComboBoxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCidadeActionPerformed

    private void jRadioButtonMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMasculinoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (!validacoes()){
           return;
       }
       JOptionPane.showMessageDialog(null,"Cadastro realizado!");
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SistemaTela2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupFeminino;
    private javax.swing.ButtonGroup buttonGroupMasculino;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBoxCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JRadioButton jRadioButtonFeminino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

    
}
